### ISSUE TITLE
有关论文中的细节

### ISSUE THREAD

**Issue by luwanglin** [yellowtownhz/3DLocalCNN#1]
> The architecture of our localization module is detailed
in the Table1 in the supplementary details. Batch Normal-
ization and ReLU non-linearity are adopted after input and
each convolutional layer. Notably, to ensure that the global
path focuses on representation only, gradients of this mod-
ule are not propagated to the global path.

想请问下这个补充细节的表格1在哪里找到，论文中只有一个表格1 是用来展示准确率结果的。谢谢

**Comment by JinkaiZheng** [comment]
您的邮件已收到！~
